# contentwrapper configuration

namespace:      BackBee\ClassContent
protocol:       bb.class
adapter:        BackBee\Stream\Adapter\Yaml
options:
    cache:      "@cache.bootstrap"
    dispatcher: "@event.dispatcher"