classcontent.include:
    listeners:
        - ["@listener.classcontentlistener", onInclude]

classcontent.postload:
    listeners:
        - ["@listener.classcontentlistener", onPostload]

classcontent.onflush:
    listeners:
        - ["@listener.classcontentlistener", onFlushContent]
        - ["@listener.revisionlistener", onFlushContent]
        - ["@listener.indexationlistener", onFlushContent]
        - ["@cache.listener", onFlushContent]
        - ["@listener.rewritinglitener", onFlushContent]
        - [BackBee\MetaData\Listener\MetaDataListener, onFlushContent, -100]

classcontent.prerender:
    listeners:
        - ["@listener.revisionlistener", onPrerenderContent]
        - ["@cache.listener", onPreRenderContent]

classcontent.postrender:
    listeners:
        - ["@cache.listener", onPostRenderContent]

rest.controller.classcontentcontroller.getaction.postcall:
    listeners:
        - ["@listener.classcontentlistener", onPostCall]

element.file.postremove:
    listeners:
        - ["@listener.classcontentlistener", onRemoveElementFile]

nestednode.page.prerender:
    listeners:
        - ["@cache.listener", onPreRenderPage]

nestednode.section.preupdate:
     listeners:
         - [BackBee\Event\Listener\PageListener, onPreUpdate]

nestednode.page.preupdate:
    listeners:
        - [BackBee\Event\Listener\PageListener, onPreUpdate]
        - ["@listener.workflowlistener", onPreUpdate]

nestednode.page.postrender:
    listeners:
        - ["@cache.listener", onPostRenderPage]

nestednode.page.onflush:
    listeners:
        - [BackBee\Event\Listener\PageListener, onFlushPage]
        - ["@listener.indexationlistener", onFlushPage]
        - ["@cache.listener", onFlushPage]
        - ["@listener.rewritinglitener", onFlushPage]
        - [BackBee\MetaData\Listener\MetaDataListener, onFlushPage, -100]

site.layout.prepersist:
    listeners:
        - [BackBee\Event\Listener\LayoutListener, onBeforeSave]

site.layout.preupdate:
    listeners:
        - [BackBee\Event\Listener\LayoutListener, onBeforeSave]

site.layout.postremove:
    listeners:
        - [BackBee\Event\Listener\LayoutListener, onAfterRemove]

revision.postload:
    listeners:
        - ["@listener.revisionlistener", onPostLoad]

revision.onflush:
    listeners:
        - ["@listener.revisionlistener", onFlushElementFile]

element.keyword.render:
    listeners:
        - [BackBee\Event\Listener\elementListener, onRender]

frontcontroller.request:
    listeners:
        - ["@rest.listener.body", onRequest]

kernel.request:
    listeners:
        - ["@profiler.listener", onKernelRequest]

kernel.exception:
    listeners:
        - ["@rest.listener.exception", onKernelException]
        - ["@exception.listener", onKernelException]

kernel.controller:
    listeners:
        - ["@rest.listener.param_converter", onKernelController]
        - ["@rest.listener.security", onKernelController]
        - ["@rest.listener.validation", onKernelController]
        - ["@rest.listener.pagination", onKernelController]

kernel.response:
    listeners:
        - ["@profiler.toolbar.listener", onKernelResponse]
        - ["@profiler.listener", onKernelResponse]

nestednode.page.postload:
    listeners:
        - ["@nestednode.page_listener", onPostLoad]

service.tagged.config_per_site:
    listeners:
        - ["@config.configurator", onGetServiceConfig]

bbapplication.init:
    listeners:
        - [BackBee\DependencyInjection\Listener\ContainerListener, onApplicationInit, -8000]
        - ["@listener.classcontentlistener", onApplicationInit]
        - [BackBee\Renderer\Listener\TwigListener, onApplicationReady]

bbapplication.stop:
    listeners:
        - ["@listener.bundlelistener", onApplicationStop]
